document.write("hello world");
document.write("<br>");
var a , b,c;
a= 50;
b=30;
c=a+b;
document.write(c);
document.write("<br>");
var a=5;
var b=4;
var c=a+b;
document.write(c);
document.write("<br>");
var a=5;
var b=4;
var c=a-b;
document.write(c);
document.write("<br>");
var a=5;
var b=4;
var c=a*b;
document.write(c);
document.write("<br>");
var a=5;
var b=4;
var c=a/b;
document.write(c);
document.write("<br>");
var a=5;
var b=4;
var c=a%b;
document.write(c);
var a=10;
var b=10;
var c=a+b;
console.log(c);
var a=10;
var b=10;
console.log(a==b);
var a=10;
var b=20;
console.log(a==b);
console.log(null==undefined);
document.write("data type");
console.log(null===undefined);
document.write("<br>");
var a=100;
var b=50;
if(a>b){
    document.write("a is greater than b");
}
