console.log("tariq");
var a =  ["usman","arslan","zeeshan"];
document.write(a + "<br>");
a.sort();
document.write(a + "<br>");
document.write("<br>");
var b=  ["natasha","arslan","warisha","tariq","jawaria","amara","sobia","nadia"];
document.write(b + "<br>");
b.sort();
document.write(b + "<br>");
document.write("<br>");
var c = ["school","college"];
document.write(c + "<br><br>");
c.pop();
document.write(c +"<br><br>");
c.push("university");
document.write(c + "<br><br>");